### ISSUE TITLE
examples & help

### ISSUE THREAD

**Issue by sjz** [stjohncj/RESTRack#1]
I'm looking at using this for a Javascript MVC app (probably angularjs), but am new to the whole ruby ecosystem and just generally quite confused by all this :smile:

What do I need to do to serve up a basic static html page and a bunch of other assets?

Would I need to create a view using builder, or use RESTRack in conjunction with something else like sinatra?

A basic example would be much appreciated or, in lieu, a brief explanation (I've looked at the tests and haven't seen one that's seems applicable to what I need)

P.S. thanks for such a cool system

**Comment by stjohncj** [comment]
RESTRack would be for serving your data in response to user input.  Typically this would be served up by a small web server that would sit behind apache or nginx that would serve your static content and also proxy requests to your rack app.

**Comment by sjz** [comment]
Makes perfect sense. Thanks :smile:

**Comment by stjohncj** [comment]
I should also point you at the group repo, this one is my personal: https://github.com/RESTRack/RESTRack

Thanks for your interest!
